Status: 1
Theme: Default
Universities:
- Acadia Univ.
- Algoma Univ.
- Athabasca Univ.
- Bishop's Univ.
- Brandon Univ.
- Brock Univ.
- Cape Breton Univ.
- Capilano Univ.
- Carleton Univ.
- Concordia Univ.
- Concordia Univ. of Edmonton
- Dalhousie Univ.
- "\xC9cole nationale d'administration publique"
- "\xC9cole de technologie sup\xE9rieure"
- "HEC Montr\xE9al"
- Institut national de la recherche scientifique
- Kwantlen Polytechnic Univ.
- Lakehead Univ.
- Laurentian Univ.
- MacEwan Univ
- McGill Univ.
- McMaster Univ.
- Memorial Univ. of Newfoundland
- Mount Allison Univ.
- Mount Royal Univ.
- Mount Saint Vincent Univ.
- Nipissing Univ.
- NSCAD Univ.
- OCAD Univ.
- "Polytechnique Montr\xE9al"
- Queen's University
- Royal Military College
- Royal Roads Univ.
- Ryerson Univ.
- Saint Mary's Univ.
- Simon Fraser Univ.
- St. Francis Xavier Univ.
- "T\xC9LUQ"
- The King's Univ.
- Thompson Rivers Univ.
- Trent Univ.
- Trinity Western Univ.
- Univ. de Moncton
- "Univ. de Montr\xE9al"
- Univ. de Sherbrooke
- "Univ. du Qu\xE9bec \xE0 Chicoutimi"
- "Univ. du Qu\xE9bec \xE0 Montr\xE9al"
- "Univ. du Qu\xE9bec \xE0 Rimouski"
- "Univ. du Qu\xE9bec \xE0 Trois-Rivi\xE8res"
- "Univ. du Qu\xE9bec en Abitibi-T\xE9miscamingue"
- "Univ. du Qu\xE9bec en Outaouais"
- Univ. Laval
- Univ. Sainte-Anne
- Univ. of Alberta
- Univ. of British Columbia
- Univ. of Calgary
- Univ. of Guelph
- Univ. of Lethbridge
- Univ. of Manitoba
- Univ. of New Brunswick
- Univ. of Northern British Columbia
- Univ. of Ontario Institute of Technology
- Univ. of Ottawa
- Univ. of Prince Edward Island
- Univ. of Regina
- Univ. of Saskatchewan
- Univ. of the Fraser Valley
- Univ. of Toronto
- Univ. of Victoria
- Univ. of Waterloo
- Univ. of Windsor
- Univ. of Wininpeg
- Vancouver Island Univ.
- Western Univ.
- Wilfrid Laurier Univ.
- York Univ.
University: Acadia Univ.
excel_links:
- https://library.upei.ca/sites/default/files/CRKN_EbookPARightsTracking_TaylorFrancis_2024_02_06_2.xlsx
- https://library.upei.ca/sites/default/files/CRKN_EbookPARightsTracking_Proquest_2024_02_06_3.xlsx
link: https://library.upei.ca/test-page-ebooks-perpetual-access-project
